### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Drx51** [dradis/dradis-nmap#3]
Hy, could you tell me how to install the plugin ? Is it the same for all ? Many problems for me with the last dradis's version.

Thanks.

**Comment by etdsoft** [comment]
Hi @Drx51 sorry for the ultra long wait, it slipped through the cracks, more info on installing plugins here:

http://dradisframework.org/documentation/add-ons.html

And feel free to post on the forum:

http://discuss.dradisframework.org/
